// Master data ports and airports for Gateway resolution (Global Sea Ports & International Cargo Hubs)
export const GATEWAYS = [
  // --- Indian Subcontinent Ports ---
  { code: 'INNSA', name: 'Jawaharlal Nehru Port (JNPT), Mumbai', city: 'Navi Mumbai', country: 'India', countryCode: 'IN', type: 'PORT', lat: 18.95, lon: 72.95, modes: ['OCEAN'] },
  { code: 'INMAA', name: 'Chennai Port', city: 'Chennai', country: 'India', countryCode: 'IN', type: 'PORT', lat: 13.08, lon: 80.30, modes: ['OCEAN'] },
  { code: 'INMUN', name: 'Mundra Port', city: 'Mundra', country: 'India', countryCode: 'IN', type: 'PORT', lat: 22.84, lon: 69.71, modes: ['OCEAN'] },
  { code: 'INPAV', name: 'Pipavav Port (GPPL)', city: 'Amreli', country: 'India', countryCode: 'IN', type: 'PORT', lat: 20.92, lon: 71.50, modes: ['OCEAN'] },
  { code: 'INVIS', name: 'Visakhapatnam Port', city: 'Visakhapatnam', country: 'India', countryCode: 'IN', type: 'PORT', lat: 17.69, lon: 83.22, modes: ['OCEAN'] },
  { code: 'INKTP', name: 'Kattupalli Port', city: 'Chennai', country: 'India', countryCode: 'IN', type: 'PORT', lat: 13.27, lon: 80.31, modes: ['OCEAN'] },
  { code: 'INHAL', name: 'Haldia Dock Complex', city: 'Haldia', country: 'India', countryCode: 'IN', type: 'PORT', lat: 22.06, lon: 88.07, modes: ['OCEAN'] },
  { code: 'INCCU', name: 'Kolkata Port', city: 'Kolkata', country: 'India', countryCode: 'IN', type: 'PORT', lat: 22.54, lon: 88.32, modes: ['OCEAN'] },
  { code: 'INCOK', name: 'Cochin Port (Vallarpadam)', city: 'Kochi', country: 'India', countryCode: 'IN', type: 'PORT', lat: 9.97, lon: 76.27, modes: ['OCEAN'] },
  { code: 'INTUT', name: 'V.O. Chidambaranar Port (Tuticorin)', city: 'Tuticorin', country: 'India', countryCode: 'IN', type: 'PORT', lat: 8.76, lon: 78.13, modes: ['OCEAN'] },
  { code: 'INIXE', name: 'New Mangalore Port', city: 'Mangalore', country: 'India', countryCode: 'IN', type: 'PORT', lat: 12.92, lon: 74.82, modes: ['OCEAN'] },
  { code: 'INMRM', name: 'Mormugao Port', city: 'Goa', country: 'India', countryCode: 'IN', type: 'PORT', lat: 15.41, lon: 73.80, modes: ['OCEAN'] },
  { code: 'INKRP', name: 'Krishnapatnam Port', city: 'Nellore', country: 'India', countryCode: 'IN', type: 'PORT', lat: 14.25, lon: 80.12, modes: ['OCEAN'] },
  { code: 'INHZR', name: 'Hazira Port', city: 'Surat', country: 'India', countryCode: 'IN', type: 'PORT', lat: 21.12, lon: 72.63, modes: ['OCEAN'] },
  { code: 'LKCMB', name: 'Port of Colombo', city: 'Colombo', country: 'Sri Lanka', countryCode: 'LK', type: 'PORT', lat: 6.95, lon: 79.85, modes: ['OCEAN'] },
  { code: 'BDCGP', name: 'Chattogram Port (Chittagong)', city: 'Chittagong', country: 'Bangladesh', countryCode: 'BD', type: 'PORT', lat: 22.32, lon: 91.80, modes: ['OCEAN'] },
  { code: 'PKKHI', name: 'Port of Karachi / Port Qasim', city: 'Karachi', country: 'Pakistan', countryCode: 'PK', type: 'PORT', lat: 24.80, lon: 66.98, modes: ['OCEAN'] },

  // --- Middle East & Gulf Ports ---
  { code: 'AEJEA', name: 'Jebel Ali Port', city: 'Dubai', country: 'UAE', countryCode: 'AE', type: 'PORT', lat: 24.98, lon: 55.06, modes: ['OCEAN'] },
  { code: 'AEAUH', name: 'Abu Dhabi (Khalifa Port)', city: 'Abu Dhabi', country: 'UAE', countryCode: 'AE', type: 'PORT', lat: 24.82, lon: 54.65, modes: ['OCEAN'] },
  { code: 'AEKLF', name: 'Khor Fakkan Container Terminal', city: 'Sharjah', country: 'UAE', countryCode: 'AE', type: 'PORT', lat: 25.35, lon: 56.35, modes: ['OCEAN'] },
  { code: 'SAJED', name: 'King Abdulaziz Port (Jeddah)', city: 'Jeddah', country: 'Saudi Arabia', countryCode: 'SA', type: 'PORT', lat: 21.51, lon: 39.16, modes: ['OCEAN'] },
  { code: 'SADMN', name: 'King Abdulaziz Port (Dammam)', city: 'Dammam', country: 'Saudi Arabia', countryCode: 'SA', type: 'PORT', lat: 26.44, lon: 50.20, modes: ['OCEAN'] },
  { code: 'OMSLL', name: 'Port of Salalah', city: 'Salalah', country: 'Oman', countryCode: 'OM', type: 'PORT', lat: 16.94, lon: 54.01, modes: ['OCEAN'] },
  { code: 'OMSOH', name: 'Port of Sohar', city: 'Sohar', country: 'Oman', countryCode: 'OM', type: 'PORT', lat: 24.50, lon: 56.63, modes: ['OCEAN'] },
  { code: 'QAHMD', name: 'Hamad Port', city: 'Doha', country: 'Qatar', countryCode: 'QA', type: 'PORT', lat: 25.02, lon: 51.60, modes: ['OCEAN'] },
  { code: 'KWSWK', name: 'Port of Shuwaikh', city: 'Kuwait City', country: 'Kuwait', countryCode: 'KW', type: 'PORT', lat: 29.35, lon: 47.93, modes: ['OCEAN'] },
  { code: 'BHKBS', name: 'Khalifa Bin Salman Port', city: 'Hidd', country: 'Bahrain', countryCode: 'BH', type: 'PORT', lat: 26.18, lon: 50.68, modes: ['OCEAN'] },

  // --- Southeast & East Asia Ports ---
  { code: 'SGSIN', name: 'Port of Singapore (PSA)', city: 'Singapore', country: 'Singapore', countryCode: 'SG', type: 'PORT', lat: 1.26, lon: 103.84, modes: ['OCEAN'] },
  { code: 'MYPKG', name: 'Port Klang (Westports & Northport)', city: 'Port Klang', country: 'Malaysia', countryCode: 'MY', type: 'PORT', lat: 3.01, lon: 101.39, modes: ['OCEAN'] },
  { code: 'MYTPP', name: 'Port of Tanjung Pelepas (PTP)', city: 'Johor', country: 'Malaysia', countryCode: 'MY', type: 'PORT', lat: 1.37, lon: 103.55, modes: ['OCEAN'] },
  { code: 'THBKK', name: 'Laem Chabang / Bangkok Port', city: 'Chonburi', country: 'Thailand', countryCode: 'TH', type: 'PORT', lat: 13.08, lon: 100.88, modes: ['OCEAN'] },
  { code: 'VNHPH', name: 'Hai Phong Port (Lach Huyen)', city: 'Hai Phong', country: 'Vietnam', countryCode: 'VN', type: 'PORT', lat: 20.84, lon: 106.69, modes: ['OCEAN'] },
  { code: 'VNSGN', name: 'Ho Chi Minh City (Cat Lai & Cai Mep)', city: 'Ho Chi Minh City', country: 'Vietnam', countryCode: 'VN', type: 'PORT', lat: 10.75, lon: 106.78, modes: ['OCEAN'] },
  { code: 'IDTPP', name: 'Tanjung Priok', city: 'Jakarta', country: 'Indonesia', countryCode: 'ID', type: 'PORT', lat: -6.10, lon: 106.88, modes: ['OCEAN'] },
  { code: 'PHMNL', name: 'Port of Manila (MICT)', city: 'Manila', country: 'Philippines', countryCode: 'PH', type: 'PORT', lat: 14.58, lon: 120.97, modes: ['OCEAN'] },
  { code: 'CNSHA', name: 'Port of Shanghai (Yangshan)', city: 'Shanghai', country: 'China', countryCode: 'CN', type: 'PORT', lat: 30.62, lon: 122.07, modes: ['OCEAN'] },
  { code: 'CNNBO', name: 'Port of Ningbo-Zhoushan', city: 'Ningbo', country: 'China', countryCode: 'CN', type: 'PORT', lat: 29.92, lon: 121.63, modes: ['OCEAN'] },
  { code: 'CNSZX', name: 'Port of Shenzhen (Yantian & Shekou)', city: 'Shenzhen', country: 'China', countryCode: 'CN', type: 'PORT', lat: 22.58, lon: 114.26, modes: ['OCEAN'] },
  { code: 'CNGGZ', name: 'Port of Guangzhou (Nansha)', city: 'Guangzhou', country: 'China', countryCode: 'CN', type: 'PORT', lat: 22.73, lon: 113.62, modes: ['OCEAN'] },
  { code: 'CNTAO', name: 'Port of Qingdao', city: 'Qingdao', country: 'China', countryCode: 'CN', type: 'PORT', lat: 36.07, lon: 120.32, modes: ['OCEAN'] },
  { code: 'CNTNJ', name: 'Port of Tianjin (Xingang)', city: 'Tianjin', country: 'China', countryCode: 'CN', type: 'PORT', lat: 38.98, lon: 117.75, modes: ['OCEAN'] },
  { code: 'CNXMN', name: 'Port of Xiamen', city: 'Xiamen', country: 'China', countryCode: 'CN', type: 'PORT', lat: 24.48, lon: 118.08, modes: ['OCEAN'] },
  { code: 'HKHKG', name: 'Port of Hong Kong (Kwai Tsing)', city: 'Hong Kong', country: 'Hong Kong', countryCode: 'HK', type: 'PORT', lat: 22.35, lon: 114.12, modes: ['OCEAN'] },
  { code: 'KRPUS', name: 'Port of Busan', city: 'Busan', country: 'South Korea', countryCode: 'KR', type: 'PORT', lat: 35.07, lon: 128.98, modes: ['OCEAN'] },
  { code: 'KRINC', name: 'Port of Incheon', city: 'Incheon', country: 'South Korea', countryCode: 'KR', type: 'PORT', lat: 37.45, lon: 126.60, modes: ['OCEAN'] },
  { code: 'JPTYO', name: 'Port of Tokyo', city: 'Tokyo', country: 'Japan', countryCode: 'JP', type: 'PORT', lat: 35.62, lon: 139.75, modes: ['OCEAN'] },
  { code: 'JPYOK', name: 'Port of Yokohama', city: 'Yokohama', country: 'Japan', countryCode: 'JP', type: 'PORT', lat: 35.45, lon: 139.64, modes: ['OCEAN'] },
  { code: 'JPKOB', name: 'Port of Kobe', city: 'Kobe', country: 'Japan', countryCode: 'JP', type: 'PORT', lat: 34.68, lon: 135.20, modes: ['OCEAN'] },
  { code: 'TWKHH', name: 'Port of Kaohsiung', city: 'Kaohsiung', country: 'Taiwan', countryCode: 'TW', type: 'PORT', lat: 22.62, lon: 120.28, modes: ['OCEAN'] },

  // --- European Ports ---
  { code: 'NLRTM', name: 'Port of Rotterdam', city: 'Rotterdam', country: 'Netherlands', countryCode: 'NL', type: 'PORT', lat: 51.95, lon: 4.14, modes: ['OCEAN'] },
  { code: 'NLAMS', name: 'Port of Amsterdam', city: 'Amsterdam', country: 'Netherlands', countryCode: 'NL', type: 'PORT', lat: 52.38, lon: 4.90, modes: ['OCEAN'] },
  { code: 'BEANR', name: 'Port of Antwerp-Bruges', city: 'Antwerp', country: 'Belgium', countryCode: 'BE', type: 'PORT', lat: 51.30, lon: 4.38, modes: ['OCEAN'] },
  { code: 'DEHAM', name: 'Port of Hamburg', city: 'Hamburg', country: 'Germany', countryCode: 'DE', type: 'PORT', lat: 53.54, lon: 9.99, modes: ['OCEAN'] },
  { code: 'DEBRV', name: 'Port of Bremerhaven', city: 'Bremerhaven', country: 'Germany', countryCode: 'DE', type: 'PORT', lat: 53.55, lon: 8.58, modes: ['OCEAN'] },
  { code: 'GBLGP', name: 'Port of Felixstowe', city: 'Felixstowe', country: 'United Kingdom', countryCode: 'GB', type: 'PORT', lat: 51.97, lon: 1.33, modes: ['OCEAN'] },
  { code: 'GBSOU', name: 'Port of Southampton', city: 'Southampton', country: 'United Kingdom', countryCode: 'GB', type: 'PORT', lat: 50.90, lon: -1.40, modes: ['OCEAN'] },
  { code: 'GBLON', name: 'London Gateway Port', city: 'London', country: 'United Kingdom', countryCode: 'GB', type: 'PORT', lat: 51.50, lon: 0.47, modes: ['OCEAN'] },
  { code: 'FRLEH', name: 'Port of Le Havre (HAROPA)', city: 'Le Havre', country: 'France', countryCode: 'FR', type: 'PORT', lat: 49.48, lon: 0.12, modes: ['OCEAN'] },
  { code: 'FRMRS', name: 'Port of Marseille-Fos', city: 'Marseille', country: 'France', countryCode: 'FR', type: 'PORT', lat: 43.40, lon: 4.90, modes: ['OCEAN'] },
  { code: 'ESVLC', name: 'Port of Valencia', city: 'Valencia', country: 'Spain', countryCode: 'ES', type: 'PORT', lat: 39.45, lon: -0.32, modes: ['OCEAN'] },
  { code: 'ESBCN', name: 'Port of Barcelona', city: 'Barcelona', country: 'Spain', countryCode: 'ES', type: 'PORT', lat: 41.35, lon: 2.17, modes: ['OCEAN'] },
  { code: 'ESALG', name: 'Port of Algeciras', city: 'Algeciras', country: 'Spain', countryCode: 'ES', type: 'PORT', lat: 36.13, lon: -5.43, modes: ['OCEAN'] },
  { code: 'ITGOA', name: 'Port of Genoa', city: 'Genoa', country: 'Italy', countryCode: 'IT', type: 'PORT', lat: 44.40, lon: 8.90, modes: ['OCEAN'] },
  { code: 'ITGIT', name: 'Port of Gioia Tauro', city: 'Gioia Tauro', country: 'Italy', countryCode: 'IT', type: 'PORT', lat: 38.43, lon: 15.90, modes: ['OCEAN'] },
  { code: 'GRPIR', name: 'Port of Piraeus', city: 'Athens', country: 'Greece', countryCode: 'GR', type: 'PORT', lat: 37.95, lon: 23.63, modes: ['OCEAN'] },
  { code: 'TRMRM', name: 'Mersin International Port', city: 'Mersin', country: 'Turkey', countryCode: 'TR', type: 'PORT', lat: 36.80, lon: 34.59, modes: ['OCEAN'] },
  { code: 'TRIST', name: 'Port of Ambarli (Istanbul)', city: 'Istanbul', country: 'Turkey', countryCode: 'TR', type: 'PORT', lat: 40.97, lon: 28.68, modes: ['OCEAN'] },
  { code: 'PLGDN', name: 'Baltic Hub (Port of Gdansk)', city: 'Gdansk', country: 'Poland', countryCode: 'PL', type: 'PORT', lat: 54.38, lon: 18.67, modes: ['OCEAN'] },

  // --- North America Ports ---
  { code: 'USLAX', name: 'Port of Los Angeles', city: 'Los Angeles', country: 'USA', countryCode: 'US', type: 'PORT', lat: 33.74, lon: -118.27, modes: ['OCEAN'] },
  { code: 'USLGB', name: 'Port of Long Beach', city: 'Long Beach', country: 'USA', countryCode: 'US', type: 'PORT', lat: 33.75, lon: -118.22, modes: ['OCEAN'] },
  { code: 'USNYC', name: 'Port of New York & New Jersey', city: 'New York', country: 'USA', countryCode: 'US', type: 'PORT', lat: 40.67, lon: -74.11, modes: ['OCEAN'] },
  { code: 'USSAV', name: 'Port of Savannah', city: 'Savannah', country: 'USA', countryCode: 'US', type: 'PORT', lat: 31.97, lon: -81.09, modes: ['OCEAN'] },
  { code: 'USHOU', name: 'Port of Houston', city: 'Houston', country: 'USA', countryCode: 'US', type: 'PORT', lat: 29.75, lon: -95.25, modes: ['OCEAN'] },
  { code: 'USORF', name: 'Port of Virginia (Norfolk)', city: 'Norfolk', country: 'USA', countryCode: 'US', type: 'PORT', lat: 36.90, lon: -76.33, modes: ['OCEAN'] },
  { code: 'USCHS', name: 'Port of Charleston', city: 'Charleston', country: 'USA', countryCode: 'US', type: 'PORT', lat: 32.78, lon: -79.93, modes: ['OCEAN'] },
  { code: 'USSEA', name: 'Port of Seattle / Tacoma', city: 'Seattle', country: 'USA', countryCode: 'US', type: 'PORT', lat: 47.60, lon: -122.33, modes: ['OCEAN'] },
  { code: 'USOAK', name: 'Port of Oakland', city: 'Oakland', country: 'USA', countryCode: 'US', type: 'PORT', lat: 37.80, lon: -122.28, modes: ['OCEAN'] },
  { code: 'CAVAN', name: 'Port of Vancouver', city: 'Vancouver', country: 'Canada', countryCode: 'CA', type: 'PORT', lat: 49.28, lon: -123.12, modes: ['OCEAN'] },
  { code: 'CAPRR', name: 'Port of Prince Rupert', city: 'Prince Rupert', country: 'Canada', countryCode: 'CA', type: 'PORT', lat: 54.32, lon: -130.33, modes: ['OCEAN'] },
  { code: 'CAMTR', name: 'Port of Montreal', city: 'Montreal', country: 'Canada', countryCode: 'CA', type: 'PORT', lat: 45.50, lon: -73.55, modes: ['OCEAN'] },
  { code: 'MXZLO', name: 'Port of Manzanillo', city: 'Manzanillo', country: 'Mexico', countryCode: 'MX', type: 'PORT', lat: 19.05, lon: -104.32, modes: ['OCEAN'] },
  { code: 'MXLZC', name: 'Port of Lazaro Cardenas', city: 'Lazaro Cardenas', country: 'Mexico', countryCode: 'MX', type: 'PORT', lat: 17.95, lon: -102.18, modes: ['OCEAN'] },

  // --- South America, Africa & Oceania Ports ---
  { code: 'BRSSZ', name: 'Port of Santos', city: 'Santos', country: 'Brazil', countryCode: 'BR', type: 'PORT', lat: -23.96, lon: -46.33, modes: ['OCEAN'] },
  { code: 'BRPNG', name: 'Port of Paranagua', city: 'Paranagua', country: 'Brazil', countryCode: 'BR', type: 'PORT', lat: -25.50, lon: -48.50, modes: ['OCEAN'] },
  { code: 'ARBUE', name: 'Port of Buenos Aires', city: 'Buenos Aires', country: 'Argentina', countryCode: 'AR', type: 'PORT', lat: -34.60, lon: -58.37, modes: ['OCEAN'] },
  { code: 'PECLL', name: 'Port of Callao', city: 'Callao', country: 'Peru', countryCode: 'PE', type: 'PORT', lat: -12.05, lon: -77.15, modes: ['OCEAN'] },
  { code: 'CLSAI', name: 'Port of San Antonio', city: 'San Antonio', country: 'Chile', countryCode: 'CL', type: 'PORT', lat: -33.58, lon: -71.62, modes: ['OCEAN'] },
  { code: 'COCTG', name: 'Port of Cartagena', city: 'Cartagena', country: 'Colombia', countryCode: 'CO', type: 'PORT', lat: 10.40, lon: -75.50, modes: ['OCEAN'] },
  { code: 'EGPSD', name: 'Port Said East Port', city: 'Port Said', country: 'Egypt', countryCode: 'EG', type: 'PORT', lat: 31.26, lon: 32.37, modes: ['OCEAN'] },
  { code: 'EGALE', name: 'Port of Alexandria', city: 'Alexandria', country: 'Egypt', countryCode: 'EG', type: 'PORT', lat: 31.20, lon: 29.90, modes: ['OCEAN'] },
  { code: 'MATNG', name: 'Tanger Med Port', city: 'Tangier', country: 'Morocco', countryCode: 'MA', type: 'PORT', lat: 35.88, lon: -5.50, modes: ['OCEAN'] },
  { code: 'ZADUR', name: 'Port of Durban', city: 'Durban', country: 'South Africa', countryCode: 'ZA', type: 'PORT', lat: -29.87, lon: 31.02, modes: ['OCEAN'] },
  { code: 'ZACPT', name: 'Port of Cape Town', city: 'Cape Town', country: 'South Africa', countryCode: 'ZA', type: 'PORT', lat: -33.90, lon: 18.42, modes: ['OCEAN'] },
  { code: 'KEMBA', name: 'Port of Mombasa', city: 'Mombasa', country: 'Kenya', countryCode: 'KE', type: 'PORT', lat: -4.04, lon: 39.67, modes: ['OCEAN'] },
  { code: 'TZDAR', name: 'Port of Dar es Salaam', city: 'Dar es Salaam', country: 'Tanzania', countryCode: 'TZ', type: 'PORT', lat: -6.83, lon: 39.30, modes: ['OCEAN'] },
  { code: 'NGAPP', name: 'Port of Lagos (Apapa)', city: 'Lagos', country: 'Nigeria', countryCode: 'NG', type: 'PORT', lat: 6.45, lon: 3.37, modes: ['OCEAN'] },
  { code: 'NGLEK', name: 'Lekki Deep Sea Port', city: 'Lagos', country: 'Nigeria', countryCode: 'NG', type: 'PORT', lat: 6.42, lon: 3.97, modes: ['OCEAN'] },
  { code: 'GHAPA', name: 'Port of Tema', city: 'Tema', country: 'Ghana', countryCode: 'GH', type: 'PORT', lat: 5.63, lon: 0.00, modes: ['OCEAN'] },
  { code: 'DJJIB', name: 'Port of Djibouti (Doraleh)', city: 'Djibouti', country: 'Djibouti', countryCode: 'DJ', type: 'PORT', lat: 11.60, lon: 43.15, modes: ['OCEAN'] },
  { code: 'AUSYD', name: 'Port of Sydney (Botany)', city: 'Sydney', country: 'Australia', countryCode: 'AU', type: 'PORT', lat: -33.97, lon: 151.20, modes: ['OCEAN'] },
  { code: 'AUMEL', name: 'Port of Melbourne', city: 'Melbourne', country: 'Australia', countryCode: 'AU', type: 'PORT', lat: -37.82, lon: 144.93, modes: ['OCEAN'] },
  { code: 'AUBNE', name: 'Port of Brisbane', city: 'Brisbane', country: 'Australia', countryCode: 'AU', type: 'PORT', lat: -27.38, lon: 153.17, modes: ['OCEAN'] },
  { code: 'AUFRE', name: 'Port of Fremantle (Perth)', city: 'Fremantle', country: 'Australia', countryCode: 'AU', type: 'PORT', lat: -32.05, lon: 115.75, modes: ['OCEAN'] },
  { code: 'NZAKL', name: 'Port of Auckland', city: 'Auckland', country: 'New Zealand', countryCode: 'NZ', type: 'PORT', lat: -36.83, lon: 174.78, modes: ['OCEAN'] },
  { code: 'NZTRG', name: 'Port of Tauranga', city: 'Tauranga', country: 'New Zealand', countryCode: 'NZ', type: 'PORT', lat: -37.67, lon: 176.18, modes: ['OCEAN'] },

  // --- Major International Cargo Airports ---
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj Intl (BOM)', city: 'Mumbai', country: 'India', countryCode: 'IN', type: 'AIRPORT', lat: 19.09, lon: 72.87, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'DEL', name: 'Indira Gandhi International (DEL)', city: 'Delhi', country: 'India', countryCode: 'IN', type: 'AIRPORT', lat: 28.57, lon: 77.10, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'BLR', name: 'Kempegowda International Airport (BLR)', city: 'Bangalore', country: 'India', countryCode: 'IN', type: 'AIRPORT', lat: 13.20, lon: 77.71, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'MAA', name: 'Chennai International Airport (MAA)', city: 'Chennai', country: 'India', countryCode: 'IN', type: 'AIRPORT', lat: 12.99, lon: 80.17, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'HYD', name: 'Rajiv Gandhi International (HYD)', city: 'Hyderabad', country: 'India', countryCode: 'IN', type: 'AIRPORT', lat: 17.24, lon: 78.43, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'CCU', name: 'Netaji Subhash Chandra Bose Intl (CCU)', city: 'Kolkata', country: 'India', countryCode: 'IN', type: 'AIRPORT', lat: 22.65, lon: 88.45, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'AMD', name: 'Sardar Vallabhbhai Patel Intl (AMD)', city: 'Ahmedabad', country: 'India', countryCode: 'IN', type: 'AIRPORT', lat: 23.08, lon: 72.63, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'COK', name: 'Cochin International Airport (COK)', city: 'Kochi', country: 'India', countryCode: 'IN', type: 'AIRPORT', lat: 10.16, lon: 76.39, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'DXB', name: 'Dubai International Airport (DXB)', city: 'Dubai', country: 'UAE', countryCode: 'AE', type: 'AIRPORT', lat: 25.25, lon: 55.37, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'DWC', name: 'Al Maktoum International (DWC)', city: 'Dubai', country: 'UAE', countryCode: 'AE', type: 'AIRPORT', lat: 24.90, lon: 55.16, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'AUH', name: 'Zayed International Airport (AUH)', city: 'Abu Dhabi', country: 'UAE', countryCode: 'AE', type: 'AIRPORT', lat: 24.43, lon: 54.65, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SHJ', name: 'Sharjah International Airport (SHJ)', city: 'Sharjah', country: 'UAE', countryCode: 'AE', type: 'AIRPORT', lat: 25.33, lon: 55.52, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'DOH', name: 'Hamad International Airport (DOH)', city: 'Doha', country: 'Qatar', countryCode: 'QA', type: 'AIRPORT', lat: 25.27, lon: 51.61, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'RUH', name: 'King Khalid International Airport (RUH)', city: 'Riyadh', country: 'Saudi Arabia', countryCode: 'SA', type: 'AIRPORT', lat: 24.96, lon: 46.70, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'JED', name: 'King Abdulaziz International (JED)', city: 'Jeddah', country: 'Saudi Arabia', countryCode: 'SA', type: 'AIRPORT', lat: 21.68, lon: 39.16, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'BAH', name: 'Bahrain International Airport (BAH)', city: 'Manama', country: 'Bahrain', countryCode: 'BH', type: 'AIRPORT', lat: 26.27, lon: 50.63, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'KWI', name: 'Kuwait International Airport (KWI)', city: 'Kuwait City', country: 'Kuwait', countryCode: 'KW', type: 'AIRPORT', lat: 29.23, lon: 47.97, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SIN', name: 'Singapore Changi Airport (SIN)', city: 'Singapore', country: 'Singapore', countryCode: 'SG', type: 'AIRPORT', lat: 1.36, lon: 103.99, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'HKG', name: 'Hong Kong International Airport (HKG)', city: 'Hong Kong', country: 'Hong Kong', countryCode: 'HK', type: 'AIRPORT', lat: 22.31, lon: 113.92, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'PVG', name: 'Shanghai Pudong International (PVG)', city: 'Shanghai', country: 'China', countryCode: 'CN', type: 'AIRPORT', lat: 31.14, lon: 121.81, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'PEK', name: 'Beijing Capital International (PEK)', city: 'Beijing', country: 'China', countryCode: 'CN', type: 'AIRPORT', lat: 40.08, lon: 116.60, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'CAN', name: 'Guangzhou Baiyun International (CAN)', city: 'Guangzhou', country: 'China', countryCode: 'CN', type: 'AIRPORT', lat: 23.39, lon: 113.30, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SZX', name: 'Shenzhen Baoan International (SZX)', city: 'Shenzhen', country: 'China', countryCode: 'CN', type: 'AIRPORT', lat: 22.64, lon: 113.81, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'CGO', name: 'Zhengzhou Xinzheng Intl (CGO)', city: 'Zhengzhou', country: 'China', countryCode: 'CN', type: 'AIRPORT', lat: 34.52, lon: 113.84, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'ICN', name: 'Incheon International Airport (ICN)', city: 'Seoul', country: 'South Korea', countryCode: 'KR', type: 'AIRPORT', lat: 37.46, lon: 126.44, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'NRT', name: 'Narita International Airport (NRT)', city: 'Tokyo', country: 'Japan', countryCode: 'JP', type: 'AIRPORT', lat: 35.76, lon: 140.39, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'HND', name: 'Tokyo Haneda Airport (HND)', city: 'Tokyo', country: 'Japan', countryCode: 'JP', type: 'AIRPORT', lat: 35.55, lon: 139.78, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'KIX', name: 'Kansai International Airport (KIX)', city: 'Osaka', country: 'Japan', countryCode: 'JP', type: 'AIRPORT', lat: 34.43, lon: 135.24, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'TPE', name: 'Taiwan Taoyuan International (TPE)', city: 'Taipei', country: 'Taiwan', countryCode: 'TW', type: 'AIRPORT', lat: 25.08, lon: 121.23, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'BKK', name: 'Suvarnabhumi Airport (BKK)', city: 'Bangkok', country: 'Thailand', countryCode: 'TH', type: 'AIRPORT', lat: 13.68, lon: 100.75, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'KUL', name: 'Kuala Lumpur International (KUL)', city: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'MY', type: 'AIRPORT', lat: 2.75, lon: 101.71, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SGN', name: 'Tan Son Nhat International (SGN)', city: 'Ho Chi Minh City', country: 'Vietnam', countryCode: 'VN', type: 'AIRPORT', lat: 10.82, lon: 106.65, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'HAN', name: 'Noi Bai International Airport (HAN)', city: 'Hanoi', country: 'Vietnam', countryCode: 'VN', type: 'AIRPORT', lat: 21.22, lon: 105.81, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'CGK', name: 'Soekarno-Hatta International (CGK)', city: 'Jakarta', country: 'Indonesia', countryCode: 'ID', type: 'AIRPORT', lat: -6.13, lon: 106.66, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'MNL', name: 'Ninoy Aquino International (MNL)', city: 'Manila', country: 'Philippines', countryCode: 'PH', type: 'AIRPORT', lat: 14.51, lon: 121.02, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'FRA', name: 'Frankfurt Airport (FRA)', city: 'Frankfurt', country: 'Germany', countryCode: 'DE', type: 'AIRPORT', lat: 50.04, lon: 8.56, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'LEJ', name: 'Leipzig/Halle Airport (LEJ)', city: 'Leipzig', country: 'Germany', countryCode: 'DE', type: 'AIRPORT', lat: 51.43, lon: 12.22, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'CGN', name: 'Cologne Bonn Airport (CGN)', city: 'Cologne', country: 'Germany', countryCode: 'DE', type: 'AIRPORT', lat: 50.87, lon: 7.14, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'AMS', name: 'Amsterdam Airport Schiphol (AMS)', city: 'Amsterdam', country: 'Netherlands', countryCode: 'NL', type: 'AIRPORT', lat: 52.31, lon: 4.76, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'LHR', name: 'London Heathrow Airport (LHR)', city: 'London', country: 'United Kingdom', countryCode: 'GB', type: 'AIRPORT', lat: 51.47, lon: -0.45, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'STN', name: 'London Stansted Airport (STN)', city: 'London', country: 'United Kingdom', countryCode: 'GB', type: 'AIRPORT', lat: 51.89, lon: 0.24, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'EMA', name: 'East Midlands Airport (EMA)', city: 'Derby', country: 'United Kingdom', countryCode: 'GB', type: 'AIRPORT', lat: 52.83, lon: -1.33, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'CDG', name: 'Paris Charles de Gaulle (CDG)', city: 'Paris', country: 'France', countryCode: 'FR', type: 'AIRPORT', lat: 49.01, lon: 2.55, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'BRU', name: 'Brussels Airport (BRU)', city: 'Brussels', country: 'Belgium', countryCode: 'BE', type: 'AIRPORT', lat: 50.90, lon: 4.48, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'LGG', name: 'Liège Airport (LGG)', city: 'Liège', country: 'Belgium', countryCode: 'BE', type: 'AIRPORT', lat: 50.64, lon: 5.44, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'MXP', name: 'Milan Malpensa Airport (MXP)', city: 'Milan', country: 'Italy', countryCode: 'IT', type: 'AIRPORT', lat: 45.63, lon: 8.72, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'MAD', name: 'Madrid-Barajas Airport (MAD)', city: 'Madrid', country: 'Spain', countryCode: 'ES', type: 'AIRPORT', lat: 40.50, lon: -3.57, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'IST', name: 'Istanbul Airport (IST)', city: 'Istanbul', country: 'Turkey', countryCode: 'TR', type: 'AIRPORT', lat: 41.28, lon: 28.75, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'ZRH', name: 'Zurich Airport (ZRH)', city: 'Zurich', country: 'Switzerland', countryCode: 'CH', type: 'AIRPORT', lat: 47.46, lon: 8.55, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'VIE', name: 'Vienna International (VIE)', city: 'Vienna', country: 'Austria', countryCode: 'AT', type: 'AIRPORT', lat: 48.11, lon: 16.57, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'MEM', name: 'Memphis International Airport (MEM)', city: 'Memphis', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 35.04, lon: -89.98, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SDF', name: 'Louisville Muhammad Ali Intl (SDF)', city: 'Louisville', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 38.17, lon: -85.74, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'MIA', name: 'Miami International Airport (MIA)', city: 'Miami', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 25.80, lon: -80.29, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'LAX', name: 'Los Angeles International (LAX)', city: 'Los Angeles', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 33.94, lon: -118.41, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'ORD', name: "O'Hare International Airport (ORD)", city: 'Chicago', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 41.97, lon: -87.91, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'JFK', name: 'John F. Kennedy Intl Airport (JFK)', city: 'New York', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 40.64, lon: -73.78, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'ATL', name: 'Hartsfield-Jackson Atlanta (ATL)', city: 'Atlanta', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 33.64, lon: -84.43, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'DFW', name: 'Dallas/Fort Worth International (DFW)', city: 'Dallas', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 32.90, lon: -97.04, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SFO', name: 'San Francisco International (SFO)', city: 'San Francisco', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 37.62, lon: -122.38, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SEA', name: 'Seattle-Tacoma International (SEA)', city: 'Seattle', country: 'USA', countryCode: 'US', type: 'AIRPORT', lat: 47.45, lon: -122.31, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'YYZ', name: 'Toronto Pearson International (YYZ)', city: 'Toronto', country: 'Canada', countryCode: 'CA', type: 'AIRPORT', lat: 43.68, lon: -79.62, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'YVR', name: 'Vancouver International (YVR)', city: 'Vancouver', country: 'Canada', countryCode: 'CA', type: 'AIRPORT', lat: 49.20, lon: -123.18, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'MEX', name: 'Mexico City International (MEX)', city: 'Mexico City', country: 'Mexico', countryCode: 'MX', type: 'AIRPORT', lat: 19.44, lon: -99.07, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'GRU', name: 'Sao Paulo Guarulhos Intl (GRU)', city: 'Sao Paulo', country: 'Brazil', countryCode: 'BR', type: 'AIRPORT', lat: -23.44, lon: -46.47, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'BOG', name: 'El Dorado International (BOG)', city: 'Bogota', country: 'Colombia', countryCode: 'CO', type: 'AIRPORT', lat: 4.70, lon: -74.15, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SCL', name: 'Arturo Merino Benitez Intl (SCL)', city: 'Santiago', country: 'Chile', countryCode: 'CL', type: 'AIRPORT', lat: -33.39, lon: -70.79, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'EZE', name: 'Ministro Pistarini Intl (EZE)', city: 'Buenos Aires', country: 'Argentina', countryCode: 'AR', type: 'AIRPORT', lat: -34.82, lon: -58.54, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'LIM', name: 'Jorge Chavez International (LIM)', city: 'Lima', country: 'Peru', countryCode: 'PE', type: 'AIRPORT', lat: -12.02, lon: -77.11, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'JNB', name: 'O.R. Tambo International (JNB)', city: 'Johannesburg', country: 'South Africa', countryCode: 'ZA', type: 'AIRPORT', lat: -26.14, lon: 28.25, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'NBO', name: 'Jomo Kenyatta International (NBO)', city: 'Nairobi', country: 'Kenya', countryCode: 'KE', type: 'AIRPORT', lat: -1.32, lon: 36.93, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'ADD', name: 'Addis Ababa Bole Intl (ADD)', city: 'Addis Ababa', country: 'Ethiopia', countryCode: 'ET', type: 'AIRPORT', lat: 8.98, lon: 38.80, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'CAI', name: 'Cairo International Airport (CAI)', city: 'Cairo', country: 'Egypt', countryCode: 'EG', type: 'AIRPORT', lat: 30.12, lon: 31.41, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'LOS', name: 'Murtala Muhammed International (LOS)', city: 'Lagos', country: 'Nigeria', countryCode: 'NG', type: 'AIRPORT', lat: 6.58, lon: 3.32, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'SYD', name: 'Sydney Kingsford Smith (SYD)', city: 'Sydney', country: 'Australia', countryCode: 'AU', type: 'AIRPORT', lat: -33.94, lon: 151.18, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'MEL', name: 'Melbourne Airport (MEL)', city: 'Melbourne', country: 'Australia', countryCode: 'AU', type: 'AIRPORT', lat: -37.67, lon: 144.84, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'BNE', name: 'Brisbane Airport (BNE)', city: 'Brisbane', country: 'Australia', countryCode: 'AU', type: 'AIRPORT', lat: -27.38, lon: 153.12, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'PER', name: 'Perth Airport (PER)', city: 'Perth', country: 'Australia', countryCode: 'AU', type: 'AIRPORT', lat: -31.94, lon: 115.97, modes: ['AIR', 'EXPRESS_AIR'] },
  { code: 'AKL', name: 'Auckland Airport (AKL)', city: 'Auckland', country: 'New Zealand', countryCode: 'NZ', type: 'AIRPORT', lat: -37.01, lon: 174.79, modes: ['AIR', 'EXPRESS_AIR'] }
]

// Volumetric divisors by mode
export const DIVISORS = {
  AIR: 6000,
  EXPRESS_AIR: 5000,
  GROUND_RAIL: 4500,
  OCEAN_LCL: 1000 // converts cm3 to CBM for revenue ton calc
}

// Road detour factors by country
export const DETOUR_FACTOR = {
  IN: 1.30,
  AE: 1.20,
  EU: 1.25,
  US: 1.22,
  DEFAULT: 1.30
}

// Sea distance lookup table (nautical miles)
export const SEA_DISTANCES = {
  'INNSA-AEJEA': 1205,
  'AEJEA-INNSA': 1205,
  'INNSA-NLRTM': 6400, // via Suez ~6400nm
  'NLRTM-INNSA': 6400,
  'INNSA-SGSIN': 2450,
  'SGSIN-INNSA': 2450,
  'INNSA-DEHAM': 6650,
  'DEHAM-INNSA': 6650,
  'INNSA-OMSLL': 890,
  'OMSLL-AEJEA': 640,
  'INNSA-CNSHA': 4150,
  'INNSA-USNYC': 8200,
  'INNSA-USLAX': 8320,
  'CNSHA-USLAX': 5546,
  'CNSHA-NLRTM': 10890,
  'INNSA-AUSYD': 6210,
}

// Linehaul speeds and dwell constants
export const MODE_CONSTANTS = {
  OCEAN_FCL: { linehaulSpeedNmPerDay: 400, originDwellDays: 3, destDwellDays: 3, bufferDays: 4 },
  OCEAN_LCL: { linehaulSpeedNmPerDay: 400, originDwellDays: 5, destDwellDays: 5, bufferDays: 5 },
  AIR: { linehaulSpeedKmPerHour: 800, handlingDays: 1, originDwellDays: 2, destDwellDays: 1.5, bufferDays: 2 },
  EXPRESS_AIR: { linehaulSpeedKmPerHour: 800, priority: true, originDwellDays: 0.5, destDwellDays: 0.5, bufferDays: 1 },
  GROUND_RAIL: { roadKmPerDay: 450, railKmPerDay: 600, originDwellDays: 0.5, destDwellDays: 0.5, bufferDays: 2 }
}

export const ContainerPayloadLimits = {
  '20GP': 21800,
  '40GP': 26600,
  '40HC': 28800,
  '20RF': 21000,
  '40RF': 27000,
  '20OT': 21500,
  '40FR': 31000
}
